<?php

namespace App\Helpers;

class PermissionHelper
{
    protected static $arabicMap = [
        'roles' => 'الأدوار',
        'edit permissions' => 'تعديل الصلاحيات',
        'add role' => 'إضافة دور',
        'edit category' => 'تعديل القسم',
        'add discount' => 'إضافة خصم',
        'disable discount' => 'تعطيل الخصم',
        'edit admin' => 'تعديل مشرف',
        'add admin' => 'إضافة مشرف',
        'add seller' => 'إضافة بائع',
        'edit seller status' => 'تعديل حالة البائع',
        'edit seller' => 'تعديل بائع',
        'edit driver' => 'تعديل سائق',
        'add driver' => 'إضافة سائق',
        'edit driver status' => 'تعديل حالة السائق',
        'add notification' => 'إضافة إشعار',
        'delete notification' => 'حذف إشعار',
        'cancel order' => 'إلغاء الطلب',
        'edit order status' => 'تعديل حالة الطلب',
        'assign order driver' => 'تعيين سائق للطلب',
        'change product status' => 'تغيير حالة المنتج',
        'add category' => 'إضافة قسم',
        'manage-employees' => 'إدارة الموظفين',
        'manage-roles' => 'إدارة الأدوار',
        'manage-products' => 'إدارة المنتجات',
        'manage-orders' => 'إدارة الطلبات',
        'manage-settings' => 'إدارة الإعدادات',
        'create admin' => 'إنشاء مشرف',
        'update admin' => 'تعديل مشرف',
        'delete admin' => 'حذف مشرف',
        'create client' => 'إنشاء عميل',
        'update client' => 'تعديل عميل',
        'reset client password' => 'إعادة تعيين كلمة مرور العميل',
        'create seller' => 'إنشاء بائع',
        'update seller' => 'تعديل بائع',
        'change seller status' => 'تغيير حالة البائع',
        'create driver' => 'إنشاء سائق',
        'update driver' => 'تعديل سائق',
        'change driver status' => 'تغيير حالة السائق',
        'create category' => 'إنشاء قسم',
        'update category' => 'تعديل قسم',
        'delete category' => 'حذف قسم',
        'create attribute' => 'إنشاء خاصية',
        'update attribute' => 'تعديل خاصية',
        'toggle attribute' => 'تفعيل/تعطيل خاصية',
        'delete attribute' => 'حذف خاصية',
        'create category attribute' => 'ربط خاصية بقسم',
        'update category attribute' => 'تعديل خاصية قسم',
        'toggle category attribute' => 'تفعيل/تعطيل خاصية قسم',
        'delete category attribute' => 'حذف خاصية قسم',
        'create ad type' => 'إنشاء نوع إعلان',
        'update ad type' => 'تعديل نوع إعلان',
        'toggle ad type' => 'تفعيل/تعطيل نوع إعلان',
        'create banner' => 'إنشاء بنر',
        'update banner' => 'تعديل بنر',
        'delete banner' => 'حذف بنر',
        'create slider' => 'إنشاء شريحة إعلانية',
        'update slider' => 'تعديل شريحة إعلانية',
        'delete slider' => 'حذف شريحة إعلانية',
        'create city' => 'إنشاء مدينة',
        'update city' => 'تعديل مدينة',
        'delete city' => 'حذف مدينة',
        'create discount' => 'إنشاء خصم',
        'toggle discount' => 'تفعيل/تعطيل خصم',
        'create coupon' => 'إنشاء كوبون',
        'update coupon' => 'تعديل كوبون',
        'toggle coupon' => 'تفعيل/تعطيل كوبون',
        'delete coupon' => 'حذف كوبون',
        'create notification' => 'إنشاء إشعار',
        'create rejected reason' => 'إنشاء سبب رفض',
        'update rejected reason' => 'تعديل سبب رفض',
        'toggle rejected reason' => 'تفعيل/تعطيل سبب رفض',
        'create report option' => 'إنشاء خيار إبلاغ',
        'update report option' => 'تعديل خيار إبلاغ',
        'toggle report option' => 'تفعيل/تعطيل خيار إبلاغ',
        'view report' => 'عرض الإبلاغ',
        'create role' => 'إنشاء دور',
        'update role' => 'تعديل دور',
        'update role permissions' => 'تعديل صلاحيات الدور',
        'view role' => 'عرض الدور',
        'create permission' => 'إنشاء صلاحية',
        'update permission' => 'تعديل صلاحية',
        'delete permission' => 'حذف صلاحية',
        'create event category' => 'إنشاء فئة حدث',
        'update event category' => 'تعديل فئة حدث',
        'delete event category' => 'حذف فئة حدث',
        'reorder event category' => 'إعادة ترتيب فئات الأحداث',
        'create daily event' => 'إنشاء حدث يومي',
        'change daily event status' => 'تغيير حالة الحدث اليومي',
        'delete daily event' => 'حذف حدث يومي',
        'create product' => 'إنشاء منتج',
        'update product' => 'تعديل منتج',
        'create ad' => 'إنشاء إعلان',
        'view ad' => 'عرض الإعلان',
        'change ad status' => 'تغيير حالة الإعلان',
        'manage ad sponsor' => 'إدارة رعاية الإعلان',
        'update settings' => 'تعديل الإعدادات',
        'create seller service' => 'إنشاء خدمة بائع',
        'toggle seller service' => 'تفعيل/تعطيل خدمة بائع',
        'create home page category' => 'إنشاء قسم للصفحة الرئيسية',
        'update home page category' => 'تعديل قسم للصفحة الرئيسية',
        'delete home page category' => 'حذف قسم من الصفحة الرئيسية',
        'view special request' => 'عرض الطلب الخاص',
        'generate invoice' => 'إصدار فاتورة',
        'change order status' => 'تغيير حالة الطلب',
        'manage user category limits' => 'إدارة حدود أقسام المستخدم',
    ];

    public static function translate($name)
    {
        $locale = app()->getLocale();
        if ($locale === 'ae' || $locale === 'ar') {
            return self::$arabicMap[strtolower(trim($name))] ?? $name;
        }
        return $name;
    }
}
